db:
  image: postgres:latest
  ports:
  - "5432:5432"
  volumes:
    - ./database:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: "sourcegraph"
    POSTGRES_PASSWORD: "sourcegraph"
redis:
  image: "redis:alpine"
  ports:
  - "6379:6379"